#!/usr/bin/env bash

# `commit-squash.sh` — squash the current branch into a single commit on top of
# an up-to-date main, then replace the remote branch with it.
#
# The squash commit message is generated by Claude from the full diff against
# main. Everything committed before the squash uses a fixed placeholder message,
# since those commits get collapsed away anyway.
#
# Usage: ./commit-squash.sh
#
# WARNING: this rewrites history and force-replaces the remote branch. Any open
# pull request for the branch will be closed when the remote branch is deleted.
# 
# WARNING 2: you must have the claude command line tool installed

set -euo pipefail;

# =========================================================================== #
#                                    Constants                                #
# =========================================================================== #

# Message used for the throwaway commit made before squashing.
PRE_SQUASH_MESSAGE="committing before squash";

# Message used if Claude is unavailable or returns nothing.
FALLBACK_MESSAGE="squash commit";

# Cap how much diff text gets sent to Claude.
MAX_DIFF_CHARS=100000;

# The claude runner owns the model and the prompt: it reads its content from
# tmp/input.txt and writes the answer to tmp/output.txt, both alongside its own
# script. Paths are relative to the repo root, so this must be run from there.
CLAUDE_RUNNER_DIR="./scripts/claude-runner";
CLAUDE_RUNNER="${CLAUDE_RUNNER_DIR}/main.sh";
CLAUDE_INPUT="${CLAUDE_RUNNER_DIR}/tmp/input.txt";
CLAUDE_OUTPUT="${CLAUDE_RUNNER_DIR}/tmp/output.txt";

CLAUDE_PROMPT_NAME="squash-commit-history";

# =========================================================================== #
#                                    Run                                      #
# =========================================================================== #

# -- Must be inside a git work tree -- #
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: not inside a git repository." >&2;
  exit 1;
fi

# -- Get the name of the current branch -- #
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)";
TEMP_BRANCH="${BRANCH_NAME}__temp";

if [ "$BRANCH_NAME" = "main" ]; then
  echo "Error: refusing to run on 'main'." >&2;
  exit 1;
fi

if git show-ref --verify --quiet "refs/heads/${TEMP_BRANCH}"; then
  echo "Error: branch '${TEMP_BRANCH}' already exists; delete it first." >&2
  exit 1
fi

echo "==> Squashing '${BRANCH_NAME}' into a single commit"

# -- Commit all changes -- #
git add -A
if git diff --cached --quiet; then
  echo "Nothing to commit, working tree clean."
else
  git commit -m "$PRE_SQUASH_MESSAGE"
fi

# -- Make sure origin/main is up to date before resetting onto it -- #
git fetch origin

# -- Create the temp branch holding this branch's work -- #
git checkout -b "$TEMP_BRANCH"

# -- Delete the original branch locally and remotely -- #
git branch -D "$BRANCH_NAME"
if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
  git push origin --delete "$BRANCH_NAME"
else
  echo "No remote branch '${BRANCH_NAME}' to delete, skipping."
fi

# -- Reset main to match the remote exactly -- #
git checkout main
git reset --hard HEAD
git pull

# -- Recreate the original branch off the fresh main -- #
git checkout -b "$BRANCH_NAME"

# -- Squash-merge the temp branch, staging every change made vs main -- #
git merge --squash "$TEMP_BRANCH"
if git diff --cached --quiet; then
  echo "Error: no changes to squash; '${BRANCH_NAME}' matches main." >&2
  exit 1
fi

# -- Ask Claude for a commit message describing the staged changes -- #
echo "==> Generating commit message"

DIFF_STAT="$(git diff --cached --stat || true)"
DIFF_BODY="$(git diff --cached | head -c "$MAX_DIFF_CHARS" || true)"

# Hand the diff to the runner through its input file. The old output is removed
# first so a stale answer from an earlier run can never be mistaken for a fresh
# one if the runner fails.
printf '%s\n\n%s\n' "$DIFF_STAT" "$DIFF_BODY" > "$CLAUDE_INPUT";
rm -f "$CLAUDE_OUTPUT";

bash "$CLAUDE_RUNNER" "$CLAUDE_PROMPT_NAME" || true;

MESSAGE=""
if [ -s "$CLAUDE_OUTPUT" ]; then
  # Drop any code fences Claude may wrap the message in, plus blank edges.
  MESSAGE="$(sed -e '/^```/d' -e 's/[[:space:]]*$//' "$CLAUDE_OUTPUT")";
fi

if [ -z "$MESSAGE" ]; then
  echo "Warning: using fallback commit message '${FALLBACK_MESSAGE}'." >&2;
  MESSAGE="$FALLBACK_MESSAGE";
fi

printf '%s\n' "$MESSAGE" | git commit -F -;

# -- Delete the temporary branch -- #
git branch -D "$TEMP_BRANCH";

# -- Push the rebuilt branch up as a new remote branch -- #
git push --set-upstream origin "$BRANCH_NAME";

echo "==> Done. '${BRANCH_NAME}' is now a single commit on top of main.";
